
try { app._main(); } catch (e) { console.error("An error occurred when calling (app/-main)"); throw(e); }